import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    DATABASE_URL: z.ZodString;
    CLERK_PUBLISHABLE_KEY: z.ZodString;
    CLERK_SECRET_KEY: z.ZodString;
    CLERK_WEBHOOK_SECRET: z.ZodOptional<z.ZodString>;
    FRONTEND_URL: z.ZodString;
    POLAR_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    POLAR_WEBHOOK_SECRET: z.ZodOptional<z.ZodString>;
    POLAR_API_BASE: z.ZodDefault<z.ZodString>;
    POLAR_CHECKOUT_PRODUCT_ID: z.ZodString;
    STREAM_API_KEY: z.ZodString;
    STREAM_API_SECRET: z.ZodString;
    IMAGEKIT_PUBLIC_KEY: z.ZodString;
    IMAGEKIT_PRIVATE_KEY: z.ZodString;
    IMAGEKIT_URL_ENDPOINT: z.ZodString;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    SENTRY_ENVIRONMENT: z.ZodOptional<z.ZodString>;
    SENTRY_TRACES_SAMPLE_RATE: z.ZodOptional<z.ZodNumber>;
    SENTRY_REPLAY_SAMPLE_RATE: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    DATABASE_URL: string;
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    CLERK_PUBLISHABLE_KEY: string;
    CLERK_SECRET_KEY: string;
    FRONTEND_URL: string;
    POLAR_API_BASE: string;
    POLAR_CHECKOUT_PRODUCT_ID: string;
    STREAM_API_KEY: string;
    STREAM_API_SECRET: string;
    IMAGEKIT_PUBLIC_KEY: string;
    IMAGEKIT_PRIVATE_KEY: string;
    IMAGEKIT_URL_ENDPOINT: string;
    CLERK_WEBHOOK_SECRET?: string | undefined;
    POLAR_ACCESS_TOKEN?: string | undefined;
    POLAR_WEBHOOK_SECRET?: string | undefined;
    SENTRY_DSN?: string | undefined;
    SENTRY_ENVIRONMENT?: string | undefined;
    SENTRY_TRACES_SAMPLE_RATE?: number | undefined;
    SENTRY_REPLAY_SAMPLE_RATE?: number | undefined;
}, {
    DATABASE_URL: string;
    CLERK_PUBLISHABLE_KEY: string;
    CLERK_SECRET_KEY: string;
    FRONTEND_URL: string;
    POLAR_CHECKOUT_PRODUCT_ID: string;
    STREAM_API_KEY: string;
    STREAM_API_SECRET: string;
    IMAGEKIT_PUBLIC_KEY: string;
    IMAGEKIT_PRIVATE_KEY: string;
    IMAGEKIT_URL_ENDPOINT: string;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    PORT?: number | undefined;
    CLERK_WEBHOOK_SECRET?: string | undefined;
    POLAR_ACCESS_TOKEN?: string | undefined;
    POLAR_WEBHOOK_SECRET?: string | undefined;
    POLAR_API_BASE?: string | undefined;
    SENTRY_DSN?: string | undefined;
    SENTRY_ENVIRONMENT?: string | undefined;
    SENTRY_TRACES_SAMPLE_RATE?: number | undefined;
    SENTRY_REPLAY_SAMPLE_RATE?: number | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare function loadEnv(): {
    DATABASE_URL: string;
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    CLERK_PUBLISHABLE_KEY: string;
    CLERK_SECRET_KEY: string;
    FRONTEND_URL: string;
    POLAR_API_BASE: string;
    POLAR_CHECKOUT_PRODUCT_ID: string;
    STREAM_API_KEY: string;
    STREAM_API_SECRET: string;
    IMAGEKIT_PUBLIC_KEY: string;
    IMAGEKIT_PRIVATE_KEY: string;
    IMAGEKIT_URL_ENDPOINT: string;
    CLERK_WEBHOOK_SECRET?: string | undefined;
    POLAR_ACCESS_TOKEN?: string | undefined;
    POLAR_WEBHOOK_SECRET?: string | undefined;
    SENTRY_DSN?: string | undefined;
    SENTRY_ENVIRONMENT?: string | undefined;
    SENTRY_TRACES_SAMPLE_RATE?: number | undefined;
    SENTRY_REPLAY_SAMPLE_RATE?: number | undefined;
};
export declare function getEnv(): {
    DATABASE_URL: string;
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    CLERK_PUBLISHABLE_KEY: string;
    CLERK_SECRET_KEY: string;
    FRONTEND_URL: string;
    POLAR_API_BASE: string;
    POLAR_CHECKOUT_PRODUCT_ID: string;
    STREAM_API_KEY: string;
    STREAM_API_SECRET: string;
    IMAGEKIT_PUBLIC_KEY: string;
    IMAGEKIT_PRIVATE_KEY: string;
    IMAGEKIT_URL_ENDPOINT: string;
    CLERK_WEBHOOK_SECRET?: string | undefined;
    POLAR_ACCESS_TOKEN?: string | undefined;
    POLAR_WEBHOOK_SECRET?: string | undefined;
    SENTRY_DSN?: string | undefined;
    SENTRY_ENVIRONMENT?: string | undefined;
    SENTRY_TRACES_SAMPLE_RATE?: number | undefined;
    SENTRY_REPLAY_SAMPLE_RATE?: number | undefined;
};
export {};
//# sourceMappingURL=env.d.ts.map